name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  regularmerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!wip automerge"
          MERGE_METHOD: "squash"
          MERGE_METHOD_LABEL_REQUIRED: "true"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
  releasemerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!wip releasemerge"
          MERGE_METHOD: "merge"
          MERGE_METHOD_LABEL_REQUIRED: "true"
          MERGE_DELETE_BRANCH: "false"
          UPDATE_METHOD: "merge"
